"""automated-migration

Revision ID: 1ff41ebb18d1
Revises: 65a9e4b7901f
Create Date: 2026-07-04 17:11:36.596305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff41ebb18d1'
down_revision: Union[str, None] = '65a9e4b7901f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiry_form_schema', sa.Column('turnstile_enabled', sa.Boolean(), nullable=True))
    op.add_column('inquiry_form_schema', sa.Column('turnstile_site_key', sa.String(length=255), nullable=True))
    op.add_column('inquiry_form_schema', sa.Column('turnstile_secret_key', sa.String(length=255), nullable=True))
    op.add_column('inquiry_form_schema', sa.Column('turnstile_mode', sa.Enum('non-interactive', 'invisible', 'managed', name='turnstile_mode_enum'), nullable=False))
    op.add_column('inquiry_form_schema', sa.Column('allowed_domains', sa.Text(), nullable=True))
    op.add_column('inquiry_form_schema', sa.Column('turnstile_verification_status', sa.Enum('pending_verification', 'verified', 'failed', name='turnstile_verification_status_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inquiry_form_schema', 'turnstile_verification_status')
    op.drop_column('inquiry_form_schema', 'allowed_domains')
    op.drop_column('inquiry_form_schema', 'turnstile_mode')
    op.drop_column('inquiry_form_schema', 'turnstile_secret_key')
    op.drop_column('inquiry_form_schema', 'turnstile_site_key')
    op.drop_column('inquiry_form_schema', 'turnstile_enabled')
    # ### end Alembic commands ###
