"""production-automated-migration

Revision ID: f3b436ce94de
Revises: ad153fb010f3
Create Date: 2026-06-08 17:08:31.866632

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3b436ce94de"
down_revision: Union[str, None] = "ad153fb010f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_inquires_data",
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )

    op.add_column(
        "client_inquires_data",
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    # Fill old rows with valid datetime
    op.execute(
        """
    UPDATE client_inquires_data
    SET 
        created_at = NOW(),
        updated_at = NOW()
    WHERE created_at IS NULL OR updated_at IS NULL
"""
    )

    # Now make created_at NOT NULL
    op.alter_column(
        "client_inquires_data",
        "created_at",
        existing_type=sa.DateTime(),
        nullable=False,
    )
    # op.drop_index("user_id", table_name="leave_balance")
    op.add_column("organization_settings", sa.Column("total_gross_hours", sa.Integer(), nullable=True))
    op.add_column("organization_settings", sa.Column("total_effective_hours", sa.Integer(), nullable=True))
    op.add_column("organization_settings", sa.Column("half_day_gross_hours", sa.Integer(), nullable=True))
    op.add_column("organization_settings", sa.Column("half_day_effective_hours", sa.Integer(), nullable=True))
    op.add_column("organization_settings", sa.Column("error_corratin_metting", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_settings", "error_corratin_metting")
    op.drop_column("organization_settings", "half_day_effective_hours")
    op.drop_column("organization_settings", "half_day_gross_hours")
    op.drop_column("organization_settings", "total_effective_hours")
    op.drop_column("organization_settings", "total_gross_hours")
    # op.create_index("user_id", "leave_balance", ["user_id"], unique=True)
    op.drop_column("client_inquires_data", "updated_at")
    op.drop_column("client_inquires_data", "created_at")
    # ### end Alembic commands ###
