"""Added The Organization Updates Table

Revision ID: 2c32bbae68e4
Revises: 8a8910550107
Create Date: 2025-06-29 14:41:53.944656

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c32bbae68e4"
down_revision: Union[str, None] = "8a8910550107"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organization_updates", sa.Column("images", sa.Text(), nullable=True))
    op.add_column("organization_updates", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "organization_updates", sa.Column("organization_id", mysql.CHAR(length=36), nullable=False)
    )
    op.add_column("organization_updates", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("organization_updates", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_organization_updates_id"), "organization_updates", ["id"], unique=False
    )
    op.create_foreign_key(
        None,
        "organization_updates",
        "organization",
        ["organization_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organization_updates", type_="foreignkey")
    op.drop_index(op.f("ix_organization_updates_id"), table_name="organization_updates")
    op.drop_column("organization_updates", "updated_at")
    op.drop_column("organization_updates", "created_at")
    op.drop_column("organization_updates", "organization_id")
    op.drop_column("organization_updates", "description")
    op.drop_column("organization_updates", "images")
    # ### end Alembic commands ###
