"""Added Some Of The Fields

Revision ID: 74aabe598cc2
Revises:
Create Date: 2025-06-23 13:40:04.823829

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = "74aabe598cc2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)

    existing_columns = [col["name"] for col in inspector.get_columns("client_inquires")]

    if "email_notification" not in existing_columns:
        op.add_column(
            "client_inquires", sa.Column("email_notification", sa.Boolean(), nullable=True)
        )

    if "authorized_recipient_emails" not in existing_columns:
        op.add_column(
            "client_inquires",
            sa.Column(
                "authorized_recipient_emails",
                sa.Text(),
                default=None,
                nullable=True,
            ),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_inquires", "authorized_recipient_emails")
    op.drop_column("client_inquires", "email_notification")
    # ### end Alembic commands ###
