"""added The Organization Holiday Section

Revision ID: 7f7aaef2d1c0
Revises: 74aabe598cc2
Create Date: 2025-06-27 15:36:25.414819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7f7aaef2d1c0'
down_revision: Union[str, None] = '74aabe598cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_holidays', sa.Column('holiday_name', sa.String(length=255), nullable=False))
    op.add_column('organization_holidays', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('organization_holidays', sa.Column('source_type', sa.Enum('default', 'user_created', name='source_type_enum'), nullable=False))
    op.add_column('organization_holidays', sa.Column('config_module_id', mysql.CHAR(length=36), nullable=False))
    op.add_column('organization_holidays', sa.Column('created_by', mysql.JSON(), nullable=True))
    op.add_column('organization_holidays', sa.Column('updated_by', mysql.JSON(), nullable=True))
    op.add_column('organization_holidays', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('organization_holidays', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_organization_holidays_id'), 'organization_holidays', ['id'], unique=False)
    op.create_foreign_key(None, 'organization_holidays', 'config_module', ['config_module_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_holidays', type_='foreignkey')
    op.drop_index(op.f('ix_organization_holidays_id'), table_name='organization_holidays')
    op.drop_column('organization_holidays', 'updated_at')
    op.drop_column('organization_holidays', 'created_at')
    op.drop_column('organization_holidays', 'updated_by')
    op.drop_column('organization_holidays', 'created_by')
    op.drop_column('organization_holidays', 'config_module_id')
    op.drop_column('organization_holidays', 'source_type')
    op.drop_column('organization_holidays', 'date')
    op.drop_column('organization_holidays', 'holiday_name')
    # ### end Alembic commands ###
