"""Added Some Field In Organization_updates

Revision ID: 8516622740c3
Revises: c1c8749ca585
Create Date: 2025-07-06 20:31:53.632601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8516622740c3'
down_revision: Union[str, None] = 'c1c8749ca585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
