"""added The year field in the holiday table

Revision ID: 8a8910550107
Revises: 7f7aaef2d1c0
Create Date: 2025-06-27 16:59:00.441998

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a8910550107"
down_revision: Union[str, None] = "7f7aaef2d1c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organization_holidays", sa.Column("year", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_holidays", "year")
    # ### end Alembic commands ###
