"""Added The Organization Updates Table

Revision ID: 9a6dc4de6a0f
Revises: 2c32bbae68e4
Create Date: 2025-06-29 15:02:16.316996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a6dc4de6a0f'
down_revision: Union[str, None] = '2c32bbae68e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_updates', sa.Column('user_id', mysql.CHAR(length=36), nullable=False))
    op.create_index(op.f('ix_organization_updates_user_id'), 'organization_updates', ['user_id'], unique=False)
    op.create_foreign_key(None, 'organization_updates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_updates', type_='foreignkey')
    op.drop_index(op.f('ix_organization_updates_user_id'), table_name='organization_updates')
    op.drop_column('organization_updates', 'user_id')
    # ### end Alembic commands ###
