"""Add Sessions table

Revision ID: b18befb035df
Revises:
Create Date: 2025-06-03 19:08:26.777050

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b18befb035df"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session", sa.Column("ip_address", sa.String(length=255), nullable=True))
    op.add_column("session", sa.Column("browser", sa.String(length=255), nullable=True))
    op.add_column("session", sa.Column("browser_version", sa.String(length=255), nullable=True))
    op.add_column("session", sa.Column("os", sa.String(length=255), nullable=True))
    op.add_column("session", sa.Column("os_version", sa.String(length=255), nullable=True))
    op.add_column("session", sa.Column("device_type", sa.String(length=255), nullable=True))
    op.add_column("session", sa.Column("is_mobile", sa.Boolean(), nullable=True))
    op.add_column("session", sa.Column("is_tablet", sa.Boolean(), nullable=True))
    op.add_column("session", sa.Column("is_pc", sa.Boolean(), nullable=True))
    op.add_column("session", sa.Column("is_bot", sa.Boolean(), nullable=True))
    op.add_column("session", sa.Column("fingerprint", sa.Boolean(), nullable=True))
    op.add_column("session", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("session", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("session", sa.Column("user_id", mysql.CHAR(length=36), nullable=False))
    op.create_foreign_key(
        None, "session", "users", ["user_id"], ["id"], onupdate="CASCADE", ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "session", type_="foreignkey")
    op.drop_column("session", "user_id")
    op.drop_column("session", "updated_at")
    op.drop_column("session", "created_at")
    op.drop_column("session", "fingerprint")
    op.drop_column("session", "is_bot")
    op.drop_column("session", "is_pc")
    op.drop_column("session", "is_tablet")
    op.drop_column("session", "is_mobile")
    op.drop_column("session", "device_type")
    op.drop_column("session", "os_version")
    op.drop_column("session", "os")
    op.drop_column("session", "browser_version")
    op.drop_column("session", "browser")
    op.drop_column("session", "ip_address")
    # ### end Alembic commands ###
