"""Added Some Field In Organization_updates

Revision ID: b2017c11bdde
Revises: cd4a467f83c0
Create Date: 2025-07-07 00:57:05.981510

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2017c11bdde"
down_revision: Union[str, None] = "cd4a467f83c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_updates",
        sa.Column(
            "source_type",
            sa.Enum("default", "system", "user_created", name="source_type_enum"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_updates", "source_type")
    # ### end Alembic commands ###
