"""Added Some Field In Organization_updates

Revision ID: cd4a467f83c0
Revises: 8516622740c3
Create Date: 2025-07-06 20:34:04.678783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4a467f83c0'
down_revision: Union[str, None] = '8516622740c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_updates', sa.Column('isCommentDisabled', sa.Boolean(), nullable=True))
    op.add_column('organization_updates', sa.Column('isLikeDisabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_updates', 'isLikeDisabled')
    op.drop_column('organization_updates', 'isCommentDisabled')
    # ### end Alembic commands ###
