"""automated-migration

Revision ID: 03526ab8617a
Revises: a211d69e594e
Create Date: 2025-08-20 11:29:10.564118

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "03526ab8617a"
down_revision: Union[str, None] = "a211d69e594e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("social_media_posts", sa.Column("selected_platforms", sa.Text(), nullable=True))
    op.add_column("social_media_posts", sa.Column("is_scheduled", sa.Boolean(), nullable=True))
    op.alter_column(
        "social_media_posts",
        "status",
        existing_type=mysql.ENUM("queued", "scheduled", "posted", "cancelled"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "social_media_posts",
        "status",
        existing_type=mysql.ENUM("queued", "scheduled", "posted", "cancelled"),
        nullable=True,
    )
    op.drop_column("social_media_posts", "is_scheduled")
    op.drop_column("social_media_posts", "selected_platforms")
    # ### end Alembic commands ###
