"""automated-migration

Revision ID: 07b84e69157f
Revises: 9603a80baee9
Create Date: 2025-12-05 14:07:54.909797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b84e69157f'
down_revision: Union[str, None] = '9603a80baee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employee_info_employee_email'), 'employee_info', ['employee_email'], unique=False)
    op.create_index(op.f('ix_organization_general_info_primary_email'), 'organization_general_info', ['primary_email'], unique=False)
    op.create_index(op.f('ix_personal_info_normalized_full_name'), 'personal_info', ['normalized_full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_info_normalized_full_name'), table_name='personal_info')
    op.drop_index(op.f('ix_organization_general_info_primary_email'), table_name='organization_general_info')
    op.drop_index(op.f('ix_employee_info_employee_email'), table_name='employee_info')
    # ### end Alembic commands ###
