"""automated-migration

Revision ID: 0ae3977fcd3e
Revises: 6362a20f8673
Create Date: 2025-10-29 17:46:04.967654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae3977fcd3e'
down_revision: Union[str, None] = '6362a20f8673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_media_posts', sa.Column('post_logs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_media_posts', 'post_logs')
    # ### end Alembic commands ###
