"""automated-migration

Revision ID: 17223d4d4040
Revises:
Create Date: 2025-07-16 19:38:05.592202

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "17223d4d4040"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("zip_code", sa.String(length=255), nullable=False),
        sa.Column("country_code", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_address_id"), "address", ["id"], unique=False)
    op.create_table(
        "organization",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("organization_created", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organization_id"), "organization", ["id"], unique=False)
    op.create_table(
        "client_inquires",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("api_secrete", sa.String(length=255), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("email_notification", sa.Boolean(), nullable=True),
        sa.Column("authorized_recipient_emails", sa.Text(), nullable=True),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_client_inquires_id"), "client_inquires", ["id"], unique=False)
    op.create_table(
        "config_module",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_config_module_id"), "config_module", ["id"], unique=False)
    op.create_table(
        "organization_about_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("about", sa.String(length=255), nullable=True),
        sa.Column("established_science", sa.DateTime(), nullable=True),
        sa.Column("registration_number", sa.String(length=255), nullable=True),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_about_info_id"), "organization_about_info", ["id"], unique=False
    )
    op.create_table(
        "organization_address",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=255), nullable=True),
        sa.Column("zip_code", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=255), nullable=True),
        sa.Column("country_code", sa.String(length=255), nullable=True),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_address_id"), "organization_address", ["id"], unique=False
    )
    op.create_table(
        "organization_contact_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("phone_number", sa.String(length=255), nullable=True),
        sa.Column("company_email", sa.String(length=255), nullable=True),
        sa.Column("country_info", mysql.JSON(), nullable=True),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_contact_info_id"), "organization_contact_info", ["id"], unique=False
    )
    op.create_table(
        "organization_general_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("organization_name", sa.String(length=255), nullable=False),
        sa.Column("primary_email", sa.String(length=255), nullable=False),
        sa.Column("primary_number", sa.String(length=255), nullable=False),
        sa.Column("country_info", mysql.JSON(), nullable=True),
        sa.Column("portal_url", sa.String(length=255), nullable=False),
        sa.Column("portal_slug", sa.String(length=255), nullable=False),
        sa.Column("website_url", sa.String(length=255), nullable=True),
        sa.Column("is_meta_verified", sa.Boolean(), nullable=False),
        sa.Column("meta_key", sa.String(length=255), nullable=False),
        sa.Column("meta_value", sa.String(length=255), nullable=False),
        sa.Column("terms_accepted", sa.Boolean(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("organization_profile_picture", sa.String(length=255), nullable=True),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_general_info_id"), "organization_general_info", ["id"], unique=False
    )
    op.create_table(
        "organization_settings",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("email_domain_slug", sa.String(length=255), nullable=True),
        sa.Column("employee_code_prefix", sa.String(length=255), nullable=True),
        sa.Column("intern_code_prefix", sa.String(length=255), nullable=True),
        sa.Column("default_timezone", sa.String(length=255), nullable=True),
        sa.Column("default_dateformat", sa.String(length=255), nullable=True),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_settings_id"), "organization_settings", ["id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("same_as_current_address", sa.Boolean(), nullable=False),
        sa.Column("current_address_id", mysql.CHAR(length=36), nullable=True),
        sa.Column("permanent_address_id", mysql.CHAR(length=36), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("account_status", sa.Boolean(), nullable=False),
        sa.Column("profile_created", sa.Boolean(), nullable=False),
        sa.Column("reset_password_token", sa.String(length=255), nullable=True),
        sa.Column("password_created", sa.Boolean(), nullable=False),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_address_id"],
            ["address.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permanent_address_id"],
            ["address.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "client_form_schema",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("field_name", sa.String(length=255), nullable=False),
        sa.Column("is_required_field", sa.Boolean(), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("default", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("config_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_module_id"], ["config_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_client_form_schema_id"), "client_form_schema", ["id"], unique=False)
    op.create_table(
        "client_inquires_data",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("data", mysql.JSON(), nullable=True),
        sa.Column("client_inquire_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_inquire_id"], ["client_inquires.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_inquires_data_id"), "client_inquires_data", ["id"], unique=False
    )
    op.create_table(
        "config_model_department",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("department_name", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("default", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("config_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_module_id"], ["config_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_config_model_department_id"), "config_model_department", ["id"], unique=False
    )
    op.create_table(
        "config_model_designations",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("designations_name", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("default", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("config_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_module_id"], ["config_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_config_model_designations_id"), "config_model_designations", ["id"], unique=False
    )
    op.create_table(
        "config_model_project_status",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("status_name", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("default", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("status_color", sa.String(length=255), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("config_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_module_id"], ["config_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_config_model_project_status_id"),
        "config_model_project_status",
        ["id"],
        unique=False,
    )
    op.create_table(
        "config_role_module",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("role_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=355), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("default", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("config_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_module_id"], ["config_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_config_role_module_id"), "config_role_module", ["id"], unique=False)
    op.create_table(
        "family_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("father_name", sa.String(length=255), nullable=False),
        sa.Column("mother_name", sa.String(length=255), nullable=False),
        sa.Column("marital_status", mysql.CHAR(length=36), nullable=False),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_family_info_id"), "family_info", ["id"], unique=False)
    op.create_table(
        "organization_holidays",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("holiday_name", sa.String(length=255), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum("default", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("config_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_module_id"], ["config_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_holidays_id"), "organization_holidays", ["id"], unique=False
    )
    op.create_table(
        "organization_updates",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("images", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("isCommentDisabled", sa.Boolean(), nullable=True),
        sa.Column("isLikeDisabled", sa.Boolean(), nullable=True),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("default", "system", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_updates_id"), "organization_updates", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_organization_updates_user_id"), "organization_updates", ["user_id"], unique=False
    )
    op.create_table(
        "personal_contact_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("personal_email", sa.String(length=255), nullable=False),
        sa.Column("mobile_number", sa.String(length=255), nullable=False),
        sa.Column("country_info", mysql.JSON(), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_personal_contact_info_id"), "personal_contact_info", ["id"], unique=False
    )
    op.create_table(
        "personal_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("middle_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("profile_picture", sa.String(length=255), nullable=True),
        sa.Column("profile_picture_bg", sa.String(length=255), nullable=True),
        sa.Column("gender", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.DateTime(), nullable=True),
        sa.Column("blood_group", sa.String(length=255), nullable=False),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_personal_info_id"), "personal_info", ["id"], unique=False)
    op.create_table(
        "session",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("ip_address", sa.String(length=255), nullable=True),
        sa.Column("browser", sa.String(length=255), nullable=True),
        sa.Column("browser_version", sa.String(length=255), nullable=True),
        sa.Column("os", sa.String(length=255), nullable=True),
        sa.Column("os_version", sa.String(length=255), nullable=True),
        sa.Column("device_type", sa.String(length=255), nullable=True),
        sa.Column("is_mobile", sa.Boolean(), nullable=True),
        sa.Column("is_tablet", sa.Boolean(), nullable=True),
        sa.Column("is_pc", sa.Boolean(), nullable=True),
        sa.Column("is_bot", sa.Boolean(), nullable=True),
        sa.Column("fingerprint", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_session_id"), "session", ["id"], unique=False)
    op.create_table(
        "social_link",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("link", sa.String(length=255), nullable=True),
        sa.Column("target_blank", sa.Boolean(), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_social_link_id"), "social_link", ["id"], unique=False)
    op.create_table(
        "children",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("child_name", sa.String(length=255), nullable=True),
        sa.Column("child_date_of_birth", sa.DateTime(), nullable=True),
        sa.Column("family_info_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_info_id"],
            ["family_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_children_id"), "children", ["id"], unique=False)
    op.create_table(
        "config_role_associated_permissions",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("module_label", sa.String(length=255), nullable=False),
        sa.Column("module_title", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("role_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("parent_module_id", mysql.CHAR(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_module_id"],
            ["config_role_associated_permissions.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_module_id"], ["config_role_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_config_role_associated_permissions_id"),
        "config_role_associated_permissions",
        ["id"],
        unique=False,
    )
    op.create_table(
        "emergency_contacts",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("emergency_contact_name", sa.String(length=255), nullable=False),
        sa.Column("emergency_contact_number", sa.String(length=255), nullable=False),
        sa.Column("emergency_contact_country_info", mysql.JSON(), nullable=True),
        sa.Column("contact_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["personal_contact_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_emergency_contacts_id"), "emergency_contacts", ["id"], unique=False)
    op.create_table(
        "employee_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("status", sa.String(length=255), nullable=False),
        sa.Column("employee_type", sa.String(length=255), nullable=True),
        sa.Column("organization_name", sa.String(length=255), nullable=False),
        sa.Column("employee_code", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=255), nullable=False),
        sa.Column("designation", sa.String(length=255), nullable=False),
        sa.Column("joining_date", sa.DateTime(), nullable=True),
        sa.Column("employee_role_id", mysql.CHAR(length=36), nullable=True),
        sa.Column("employee_email", sa.String(length=255), nullable=False),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("reporting_to_id", mysql.CHAR(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_role_id"],
            ["config_role_module.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporting_to_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_employee_info_id"), "employee_info", ["id"], unique=False)
    op.create_table(
        "permission_modules",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("is_allowed", sa.Boolean(), nullable=False),
        sa.Column("show_input", sa.Boolean(), nullable=False),
        sa.Column("associated_permissions_module_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["associated_permissions_module_id"],
            ["config_role_associated_permissions.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permission_modules_id"), "permission_modules", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_permission_modules_id"), table_name="permission_modules")
    op.drop_table("permission_modules")
    op.drop_index(op.f("ix_employee_info_id"), table_name="employee_info")
    op.drop_table("employee_info")
    op.drop_index(op.f("ix_emergency_contacts_id"), table_name="emergency_contacts")
    op.drop_table("emergency_contacts")
    op.drop_index(
        op.f("ix_config_role_associated_permissions_id"),
        table_name="config_role_associated_permissions",
    )
    op.drop_table("config_role_associated_permissions")
    op.drop_index(op.f("ix_children_id"), table_name="children")
    op.drop_table("children")
    op.drop_index(op.f("ix_social_link_id"), table_name="social_link")
    op.drop_table("social_link")
    op.drop_index(op.f("ix_session_id"), table_name="session")
    op.drop_table("session")
    op.drop_index(op.f("ix_personal_info_id"), table_name="personal_info")
    op.drop_table("personal_info")
    op.drop_index(op.f("ix_personal_contact_info_id"), table_name="personal_contact_info")
    op.drop_table("personal_contact_info")
    op.drop_index(op.f("ix_organization_updates_user_id"), table_name="organization_updates")
    op.drop_index(op.f("ix_organization_updates_id"), table_name="organization_updates")
    op.drop_table("organization_updates")
    op.drop_index(op.f("ix_organization_holidays_id"), table_name="organization_holidays")
    op.drop_table("organization_holidays")
    op.drop_index(op.f("ix_family_info_id"), table_name="family_info")
    op.drop_table("family_info")
    op.drop_index(op.f("ix_config_role_module_id"), table_name="config_role_module")
    op.drop_table("config_role_module")
    op.drop_index(
        op.f("ix_config_model_project_status_id"), table_name="config_model_project_status"
    )
    op.drop_table("config_model_project_status")
    op.drop_index(op.f("ix_config_model_designations_id"), table_name="config_model_designations")
    op.drop_table("config_model_designations")
    op.drop_index(op.f("ix_config_model_department_id"), table_name="config_model_department")
    op.drop_table("config_model_department")
    op.drop_index(op.f("ix_client_inquires_data_id"), table_name="client_inquires_data")
    op.drop_table("client_inquires_data")
    op.drop_index(op.f("ix_client_form_schema_id"), table_name="client_form_schema")
    op.drop_table("client_form_schema")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organization_settings_id"), table_name="organization_settings")
    op.drop_table("organization_settings")
    op.drop_index(op.f("ix_organization_general_info_id"), table_name="organization_general_info")
    op.drop_table("organization_general_info")
    op.drop_index(op.f("ix_organization_contact_info_id"), table_name="organization_contact_info")
    op.drop_table("organization_contact_info")
    op.drop_index(op.f("ix_organization_address_id"), table_name="organization_address")
    op.drop_table("organization_address")
    op.drop_index(op.f("ix_organization_about_info_id"), table_name="organization_about_info")
    op.drop_table("organization_about_info")
    op.drop_index(op.f("ix_config_module_id"), table_name="config_module")
    op.drop_table("config_module")
    op.drop_index(op.f("ix_client_inquires_id"), table_name="client_inquires")
    op.drop_table("client_inquires")
    op.drop_index(op.f("ix_organization_id"), table_name="organization")
    op.drop_table("organization")
    op.drop_index(op.f("ix_address_id"), table_name="address")
    op.drop_table("address")
    # ### end Alembic commands ###
