"""automated-migration

Revision ID: 208c7dc6fa03
Revises: e15e8b36b127
Create Date: 2026-06-15 09:46:34.444188

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "208c7dc6fa03"
down_revision: Union[str, None] = "e15e8b36b127"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inquiry_form_schema", "turnstile_widget_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inquiry_form_schema", sa.Column("turnstile_widget_name", mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
