"""automated-migration

Revision ID: 26c4711ba4f6
Revises: 820aac1d710d
Create Date: 2026-04-05 12:41:44.947222

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "26c4711ba4f6"
down_revision: Union[str, None] = "820aac1d710d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attendance_break_model",
        "break_end_time",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column("attendance_break_model", "punch_in_coordinates", existing_type=mysql.TEXT(), nullable=True)
    op.alter_column("attendance_break_model", "punch_out_coordinates", existing_type=mysql.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attendance_break_model",
        "punch_out_coordinates",
        existing_type=mysql.TEXT(),
        nullable=False,
    )
    op.alter_column("attendance_break_model", "punch_in_coordinates", existing_type=mysql.TEXT(), nullable=False)
    op.alter_column(
        "attendance_break_model",
        "break_end_time",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
