"""automated-migration

Revision ID: 2b619fcc6f97
Revises: 2cc6ca782693
Create Date: 2026-06-11 17:25:34.667995

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "2b619fcc6f97"
down_revision: Union[str, None] = "2cc6ca782693"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inquiry_form_schema", sa.Column("turnstile_enabled", sa.Boolean(), nullable=True))
    op.add_column("inquiry_form_schema", sa.Column("turnstile_site_key", sa.String(length=255), nullable=True))
    op.add_column("inquiry_form_schema", sa.Column("turnstile_secret_key", sa.String(length=255), nullable=True))
    op.add_column(
        "inquiry_form_schema",
        sa.Column(
            "turnstile_mode",
            sa.Enum("non-interactive", "invisible", "managed", name="turnstile_mode_enum"),
            nullable=False,
        ),
    )
    op.add_column("inquiry_form_schema", sa.Column("allowed_domains", sa.Text(), nullable=True))
    op.alter_column(
        "organization_about_info",
        "about",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization_about_info",
        "about",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("inquiry_form_schema", "allowed_domains")
    op.drop_column("inquiry_form_schema", "turnstile_mode")
    op.drop_column("inquiry_form_schema", "turnstile_secret_key")
    op.drop_column("inquiry_form_schema", "turnstile_site_key")
    op.drop_column("inquiry_form_schema", "turnstile_enabled")
    # ### end Alembic commands ###
