"""automated-migration

Revision ID: 2f6cfdc04551
Revises: 4d6e7df80eb7
Create Date: 2026-04-04 21:28:05.886175

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f6cfdc04551"
down_revision: Union[str, None] = "4d6e7df80eb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attendance_punch_in_out_module",
        sa.Column("is_work_from_home", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attendance_punch_in_out_module", "is_work_from_home")
    # ### end Alembic commands ###
