"""automated-migration

Revision ID: 33aba5a68da7
Revises: 50889b02cda7
Create Date: 2025-08-01 12:11:33.230106

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "33aba5a68da7"
down_revision: Union[str, None] = "50889b02cda7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("maintenance_logs", sa.Column("reason", sa.Text(), nullable=True))
    op.add_column("maintenance_logs", sa.Column("message", sa.Text(), nullable=True))
    op.add_column(
        "maintenance_logs", sa.Column("maintenance_mode_id", mysql.CHAR(length=36), nullable=True)
    )
    op.create_foreign_key(
        None, "maintenance_logs", "maintenance_mode", ["maintenance_mode_id"], ["id"]
    )
    op.add_column("maintenance_mode", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("maintenance_mode", sa.Column("message", sa.Text(), nullable=True))
    op.add_column("maintenance_mode", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("maintenance_mode", sa.Column("updated_by", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("maintenance_mode", "updated_by")
    op.drop_column("maintenance_mode", "updated_at")
    op.drop_column("maintenance_mode", "message")
    op.drop_column("maintenance_mode", "is_active")
    op.drop_constraint(None, "maintenance_logs", type_="foreignkey")
    op.drop_column("maintenance_logs", "maintenance_mode_id")
    op.drop_column("maintenance_logs", "message")
    op.drop_column("maintenance_logs", "reason")
    # ### end Alembic commands ###
