"""automated-migration

Revision ID: 34db61f01c25
Revises: 2277fd26f31f
Create Date: 2025-11-10 18:10:12.862487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34db61f01c25'
down_revision: Union[str, None] = '2277fd26f31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('is_paid', table_name='organization_leaves_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('is_paid', 'organization_leaves_settings', ['is_paid'], unique=True)
    # ### end Alembic commands ###
