"""automated-migration

Revision ID: 4d0cc30c6a2d
Revises: 553f490b3599
Create Date: 2026-03-29 15:19:35.622036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4d0cc30c6a2d'
down_revision: Union[str, None] = '553f490b3599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_locations_config', sa.Column('created_by', mysql.JSON(), nullable=True))
    op.add_column('organization_locations_config', sa.Column('updated_by', mysql.JSON(), nullable=True))
    op.add_column('organization_locations_config', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('organization_locations_config', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_locations_config', 'updated_at')
    op.drop_column('organization_locations_config', 'created_at')
    op.drop_column('organization_locations_config', 'updated_by')
    op.drop_column('organization_locations_config', 'created_by')
    # ### end Alembic commands ###
