"""automated-migration

Revision ID: 4d6e7df80eb7
Revises: 4d0cc30c6a2d
Create Date: 2026-03-29 15:22:22.531293

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d6e7df80eb7"
down_revision: Union[str, None] = "4d0cc30c6a2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_locations_config",
        sa.Column("allowed_radius_meters", sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_locations_config", "allowed_radius_meters")
    # ### end Alembic commands ###
