"""automated-migration

Revision ID: 50889b02cda7
Revises: a303347c6f6d
Create Date: 2025-07-17 18:51:38.383562

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "50889b02cda7"
down_revision: Union[str, None] = "a303347c6f6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orbit_admin", "otp_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orbit_admin", sa.Column("otp_code", mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
