"""automated-migration

Revision ID: 553f490b3599
Revises: 9a4f6206abb8
Create Date: 2026-03-29 11:57:06.851340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '553f490b3599'
down_revision: Union[str, None] = '9a4f6206abb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_break_model', sa.Column('session_id', mysql.CHAR(length=36), nullable=False))
    op.add_column('attendance_break_model', sa.Column('break_start_time', sa.String(length=255), nullable=False))
    op.add_column('attendance_break_model', sa.Column('break_end_time', sa.String(length=255), nullable=False))
    op.add_column('attendance_break_model', sa.Column('break_duration', sa.Float(), nullable=True))
    op.add_column('attendance_break_model', sa.Column('punch_in_coordinates', sa.Text(), nullable=False))
    op.add_column('attendance_break_model', sa.Column('punch_out_coordinates', sa.Text(), nullable=False))
    op.add_column('attendance_break_model', sa.Column('is_mislinious', sa.Boolean(), nullable=False))
    op.add_column('attendance_break_model', sa.Column('status', sa.Enum('active', 'completed', 'system_ended', name='break_status_enum'), nullable=True))
    op.create_foreign_key(None, 'attendance_break_model', 'attendance_punch_in_out_module', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('attendance_leave_module', 'status',
               existing_type=mysql.ENUM('pending', 'approved', 'cancelled', 'rejected'),
               server_default=None,
               type_=sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leave_status_enum'),
               existing_nullable=False)
    op.add_column('attendance_punch_in_out_module', sa.Column('user_id', mysql.CHAR(length=36), nullable=False))
    op.add_column('attendance_punch_in_out_module', sa.Column('punch_in_time', sa.String(length=255), nullable=False))
    op.add_column('attendance_punch_in_out_module', sa.Column('punch_out_time', sa.String(length=255), nullable=False))
    op.add_column('attendance_punch_in_out_module', sa.Column('status', sa.Enum('active', 'completed', 'system_ended', name='attendance_punch_in_out_module_status_enum'), nullable=True))
    op.add_column('attendance_punch_in_out_module', sa.Column('punch_in_coordinates', sa.Text(), nullable=False))
    op.add_column('attendance_punch_in_out_module', sa.Column('punch_out_coordinates', sa.Text(), nullable=False))
    op.add_column('attendance_punch_in_out_module', sa.Column('is_mislinious', sa.Boolean(), nullable=False))
    op.add_column('attendance_punch_in_out_module', sa.Column('total_working_hours', sa.Float(), nullable=True))
    op.add_column('attendance_punch_in_out_module', sa.Column('total_break_hours', sa.Float(), nullable=True))
    op.add_column('attendance_punch_in_out_module', sa.Column('gross_hours', sa.Float(), nullable=True))
    op.add_column('attendance_punch_in_out_module', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('attendance_punch_in_out_module', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'attendance_punch_in_out_module', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('organization_locations_config', sa.Column('location_coordinates', sa.Text(), nullable=False))
    op.add_column('organization_locations_config', sa.Column('status', sa.Boolean(), nullable=False))
    op.drop_column('organization_locations_config', 'location_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_locations_config', sa.Column('location_code', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('organization_locations_config', 'status')
    op.drop_column('organization_locations_config', 'location_coordinates')
    op.drop_constraint(None, 'attendance_punch_in_out_module', type_='foreignkey')
    op.drop_column('attendance_punch_in_out_module', 'updated_at')
    op.drop_column('attendance_punch_in_out_module', 'created_at')
    op.drop_column('attendance_punch_in_out_module', 'gross_hours')
    op.drop_column('attendance_punch_in_out_module', 'total_break_hours')
    op.drop_column('attendance_punch_in_out_module', 'total_working_hours')
    op.drop_column('attendance_punch_in_out_module', 'is_mislinious')
    op.drop_column('attendance_punch_in_out_module', 'punch_out_coordinates')
    op.drop_column('attendance_punch_in_out_module', 'punch_in_coordinates')
    op.drop_column('attendance_punch_in_out_module', 'status')
    op.drop_column('attendance_punch_in_out_module', 'punch_out_time')
    op.drop_column('attendance_punch_in_out_module', 'punch_in_time')
    op.drop_column('attendance_punch_in_out_module', 'user_id')
    op.alter_column('attendance_leave_module', 'status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leave_status_enum'),
               server_default=sa.text("'pending'"),
               type_=mysql.ENUM('pending', 'approved', 'cancelled', 'rejected'),
               existing_nullable=False)
    op.drop_constraint(None, 'attendance_break_model', type_='foreignkey')
    op.drop_column('attendance_break_model', 'status')
    op.drop_column('attendance_break_model', 'is_mislinious')
    op.drop_column('attendance_break_model', 'punch_out_coordinates')
    op.drop_column('attendance_break_model', 'punch_in_coordinates')
    op.drop_column('attendance_break_model', 'break_duration')
    op.drop_column('attendance_break_model', 'break_end_time')
    op.drop_column('attendance_break_model', 'break_start_time')
    op.drop_column('attendance_break_model', 'session_id')
    # ### end Alembic commands ###
