"""automated-migration

Revision ID: 57296bca74f8
Revises: 8f4eceb5bb44
Create Date: 2025-08-01 19:01:24.773246

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57296bca74f8"
down_revision: Union[str, None] = "8f4eceb5bb44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("maintenance_mode", sa.Column("message", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("maintenance_mode", "message")
    # ### end Alembic commands ###
