"""automated-migration

Revision ID: 57c070e75db7
Revises: 57296bca74f8
Create Date: 2025-08-04 18:30:50.101335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c070e75db7'
down_revision: Union[str, None] = '57296bca74f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_logs', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_logs', 'cancellation_reason')
    # ### end Alembic commands ###
