"""automated-migration

Revision ID: 63079e46cb44
Revises: b7d7ecb4efe3
Create Date: 2026-01-04 19:36:05.182949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63079e46cb44'
down_revision: Union[str, None] = 'b7d7ecb4efe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_leave_module', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('attendance_leave_module', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_leave_module', 'end_date',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('attendance_leave_module', 'start_date',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
