"""automated-migration

Revision ID: 74e816fc888a
Revises: a66acba7ab4e
Create Date: 2026-06-13 09:38:59.294723

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74e816fc888a"
down_revision: Union[str, None] = "a66acba7ab4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inquiry_form_schema",
        sa.Column(
            "turnstile_setup_mode", sa.Enum("automated", "manual", name="turnstile_setup_mode_enum"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inquiry_form_schema", "turnstile_setup_mode")
    # ### end Alembic commands ###
