"""automated-migration

Revision ID: 820aac1d710d
Revises: 06c46cd8bbe9
Create Date: 2026-04-04 21:42:53.018811

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "820aac1d710d"
down_revision: Union[str, None] = "06c46cd8bbe9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attendance_punch_in_out_module",
        "punch_out_coordinates",
        existing_type=mysql.TEXT(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attendance_punch_in_out_module",
        "punch_out_coordinates",
        existing_type=mysql.TEXT(),
        nullable=False,
    )
    # ### end Alembic commands ###
