"""automated-migration

Revision ID: 8417faa82538
Revises: ee80f70cc1f1
Create Date: 2025-08-07 18:23:20.671845

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8417faa82538"
down_revision: Union[str, None] = "ee80f70cc1f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("form_id", table_name="client_inquires_data")
    op.drop_index("form_name", table_name="client_inquires_data")
    op.create_unique_constraint(None, "inquiry_form_schema", ["form_id"])
    op.create_unique_constraint(None, "inquiry_form_schema", ["form_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "inquiry_form_schema", type_="unique")
    op.drop_constraint(None, "inquiry_form_schema", type_="unique")
    op.create_index("form_name", "client_inquires_data", ["form_name"], unique=True)
    op.create_index("form_id", "client_inquires_data", ["form_id"], unique=True)
    # ### end Alembic commands ###
