"""automated-migration

Revision ID: 882a5873813a
Revises: 923945ab1abb
Create Date: 2026-04-08 21:46:28.725979

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "882a5873813a"
down_revision: Union[str, None] = "923945ab1abb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attendance_break_model", sa.Column("total_break_minutes", sa.Float(), nullable=True))
    op.drop_column("attendance_break_model", "break_duration")
    op.add_column("attendance_punch_in_out_module", sa.Column("total_effective_minutes", sa.Integer(), nullable=True))
    op.add_column("attendance_punch_in_out_module", sa.Column("total_break_minutes", sa.Integer(), nullable=True))
    op.add_column("attendance_punch_in_out_module", sa.Column("total_gross_minutes", sa.Integer(), nullable=True))
    op.add_column("attendance_punch_in_out_module", sa.Column("is_regularize_required", sa.Boolean(), nullable=False))
    op.add_column("attendance_punch_in_out_module", sa.Column("session_completed", sa.Boolean(), nullable=False))
    op.drop_column("attendance_punch_in_out_module", "total_break_hours")
    op.drop_column("attendance_punch_in_out_module", "gross_hours")
    op.drop_column("attendance_punch_in_out_module", "total_working_hours")
    op.add_column("organization_settings", sa.Column("total_gross_hours", sa.Integer(), nullable=True))
    op.add_column("organization_settings", sa.Column("total_effective_hours", sa.Integer(), nullable=True))
    op.add_column("organization_settings", sa.Column("half_day_gross_hours", sa.Integer(), nullable=True))
    op.add_column("organization_settings", sa.Column("half_day_effective_hours", sa.Integer(), nullable=True))
    op.add_column("organization_settings", sa.Column("error_corratin_metting", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_settings", "error_corratin_metting")
    op.drop_column("organization_settings", "half_day_effective_hours")
    op.drop_column("organization_settings", "half_day_gross_hours")
    op.drop_column("organization_settings", "total_effective_hours")
    op.drop_column("organization_settings", "total_gross_hours")
    op.add_column("attendance_punch_in_out_module", sa.Column("total_working_hours", mysql.FLOAT(), nullable=True))
    op.add_column("attendance_punch_in_out_module", sa.Column("gross_hours", mysql.FLOAT(), nullable=True))
    op.add_column("attendance_punch_in_out_module", sa.Column("total_break_hours", mysql.FLOAT(), nullable=True))
    op.drop_column("attendance_punch_in_out_module", "session_completed")
    op.drop_column("attendance_punch_in_out_module", "is_regularize_required")
    op.drop_column("attendance_punch_in_out_module", "total_gross_minutes")
    op.drop_column("attendance_punch_in_out_module", "total_break_minutes")
    op.drop_column("attendance_punch_in_out_module", "total_effective_minutes")
    op.add_column("attendance_break_model", sa.Column("break_duration", mysql.FLOAT(), nullable=True))
    op.drop_column("attendance_break_model", "total_break_minutes")
    # ### end Alembic commands ###
