"""automated-migration

Revision ID: 8f4eceb5bb44
Revises: 33aba5a68da7
Create Date: 2025-08-01 17:50:38.348502

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8f4eceb5bb44"
down_revision: Union[str, None] = "33aba5a68da7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("maintenance_logs", "note")
    op.drop_column("maintenance_mode", "message")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("maintenance_mode", sa.Column("message", mysql.TEXT(), nullable=True))
    op.add_column("maintenance_logs", sa.Column("note", mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
