"""automated-migration

Revision ID: 923945ab1abb
Revises: 26c4711ba4f6
Create Date: 2026-04-08 21:21:41.788389

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "923945ab1abb"
down_revision: Union[str, None] = "26c4711ba4f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attendance_break_model",
        "break_start_time",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "attendance_break_model",
        "break_end_time",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "attendance_punch_in_out_module",
        "punch_in_time",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "attendance_punch_in_out_module",
        "punch_out_time",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attendance_punch_in_out_module",
        "punch_out_time",
        existing_type=sa.DateTime(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "attendance_punch_in_out_module",
        "punch_in_time",
        existing_type=sa.DateTime(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "attendance_break_model",
        "break_end_time",
        existing_type=sa.DateTime(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "attendance_break_model",
        "break_start_time",
        existing_type=sa.DateTime(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
