"""automated-migration

Revision ID: 924dad1ad813
Revises: 8c8f08b1148d
Create Date: 2025-09-20 15:23:12.033538

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "924dad1ad813"
down_revision: Union[str, None] = "8c8f08b1148d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_inquires", "email_notification")
    op.drop_column("client_inquires", "authorized_recipient_emails")
    op.add_column(
        "client_inquires_data", sa.Column("email_notification", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "client_inquires_data", sa.Column("authorized_recipient_emails", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_inquires_data", "authorized_recipient_emails")
    op.drop_column("client_inquires_data", "email_notification")
    op.add_column(
        "client_inquires", sa.Column("authorized_recipient_emails", mysql.TEXT(), nullable=True)
    )
    op.add_column(
        "client_inquires",
        sa.Column(
            "email_notification", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
