"""automated-migration

Revision ID: 9603a80baee9
Revises:
Create Date: 2025-12-04 12:35:23.436726

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9603a80baee9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("zip_code", sa.String(length=255), nullable=False),
        sa.Column("country_code", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "maintenance_mode",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orbit_admin",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("organization_created", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "client_inquires",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("api_secrete", sa.String(length=255), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config_module",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "maintenance_logs",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("started_by", sa.String(length=255), nullable=False),
        sa.Column("ended_by", sa.String(length=255), nullable=True),
        sa.Column("type", sa.Enum("manual", "scheduled", name="maintenance_type"), nullable=True),
        sa.Column(
            "status",
            sa.Enum("scheduled", "active", "completed", "cancelled", name="maintenance_status"),
            nullable=True,
        ),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("maintenance_mode_id", mysql.CHAR(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["maintenance_mode_id"],
            ["maintenance_mode.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orbit_admin_session",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("ip_address", sa.String(length=255), nullable=True),
        sa.Column("browser", sa.String(length=255), nullable=True),
        sa.Column("browser_version", sa.String(length=255), nullable=True),
        sa.Column("os", sa.String(length=255), nullable=True),
        sa.Column("os_version", sa.String(length=255), nullable=True),
        sa.Column("device_type", sa.String(length=255), nullable=True),
        sa.Column("is_mobile", sa.Boolean(), nullable=True),
        sa.Column("is_tablet", sa.Boolean(), nullable=True),
        sa.Column("is_pc", sa.Boolean(), nullable=True),
        sa.Column("is_bot", sa.Boolean(), nullable=True),
        sa.Column("fingerprint", sa.String(length=500), nullable=True),
        sa.Column("admin_signature", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("admin_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"], ["orbit_admin.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_about_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("about", sa.String(length=255), nullable=True),
        sa.Column("established_science", sa.DateTime(), nullable=True),
        sa.Column("registration_number", sa.String(length=255), nullable=True),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_address",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=255), nullable=True),
        sa.Column("zip_code", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=255), nullable=True),
        sa.Column("country_code", sa.String(length=255), nullable=True),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_contact_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("phone_number", sa.String(length=255), nullable=True),
        sa.Column("company_email", sa.String(length=255), nullable=True),
        sa.Column("country_info", mysql.JSON(), nullable=True),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_general_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("organization_name", sa.String(length=255), nullable=False),
        sa.Column("primary_email", sa.String(length=255), nullable=False),
        sa.Column("primary_number", sa.String(length=255), nullable=False),
        sa.Column("country_info", mysql.JSON(), nullable=True),
        sa.Column("portal_url", sa.String(length=255), nullable=False),
        sa.Column("portal_slug", sa.String(length=255), nullable=False),
        sa.Column("website_url", sa.String(length=255), nullable=True),
        sa.Column("is_meta_verified", sa.Boolean(), nullable=False),
        sa.Column("meta_key", sa.String(length=255), nullable=False),
        sa.Column("meta_value", sa.String(length=255), nullable=False),
        sa.Column("terms_accepted", sa.Boolean(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("industry", sa.String(length=255), nullable=False),
        sa.Column("industry_slug", sa.String(length=255), nullable=False),
        sa.Column("employee_count", sa.String(length=255), nullable=False),
        sa.Column("organization_profile_picture", sa.String(length=255), nullable=True),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_leaves_settings",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("leave_name", sa.String(length=255), nullable=False),
        sa.Column("leave_code", sa.String(length=255), nullable=False),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("max_number_of_leave", sa.Integer(), nullable=False),
        sa.Column("refill_quarterly", sa.Boolean(), nullable=False),
        sa.Column(
            "refill_from",
            sa.Enum("January", "April", "July", "October", name="refill_quarter_start_enum"),
            nullable=True,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("gender", mysql.JSON(), nullable=True),
        sa.Column("employee_status", mysql.JSON(), nullable=True),
        sa.Column("marital_status", mysql.JSON(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("leave_code"),
        sa.UniqueConstraint("leave_name"),
    )
    op.create_index(
        op.f("ix_organization_leaves_settings_organization_id"),
        "organization_leaves_settings",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "organization_settings",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("email_domain_slug", sa.String(length=255), nullable=True),
        sa.Column("employee_code_prefix", sa.String(length=255), nullable=True),
        sa.Column("intern_code_prefix", sa.String(length=255), nullable=True),
        sa.Column("default_timezone", sa.String(length=255), nullable=True),
        sa.Column("default_dateformat", sa.String(length=255), nullable=True),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_updates_admin",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("images", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("isCommentDisabled", sa.Boolean(), nullable=True),
        sa.Column("isLikeDisabled", sa.Boolean(), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("system", "announcement_team", "user", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "announcement_type",
            sa.Enum(
                "general",
                "product_update",
                "birthday_wish",
                "work_anniversary_wish",
                name="announcement_type_enum",
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["orbit_admin.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "social_media_accounts",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("platform", sa.String(length=255), nullable=True),
        sa.Column("account_name", sa.String(length=255), nullable=True),
        sa.Column("access_token", sa.String(length=255), nullable=True),
        sa.Column("refresh_token", sa.String(length=255), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("extra_data", mysql.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "social_media_posts",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("caption", sa.Text(), nullable=False),
        sa.Column("media_urls", sa.Text(), nullable=True),
        sa.Column("type", sa.Enum("default", "scheduled", name="post_type_enum"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "scheduled", "posted", "cancelled", name="post_status_enum"),
            nullable=False,
        ),
        sa.Column("post_logs", sa.Text(), nullable=True),
        sa.Column("selected_platforms", sa.Text(), nullable=True),
        sa.Column("is_scheduled", sa.Boolean(), nullable=True),
        sa.Column("scheduled_on", sa.DateTime(), nullable=True),
        sa.Column("post_publish_records", sa.Text(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("same_as_current_address", sa.Boolean(), nullable=False),
        sa.Column("current_address_id", mysql.CHAR(length=36), nullable=True),
        sa.Column("permanent_address_id", mysql.CHAR(length=36), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("account_status", sa.Boolean(), nullable=False),
        sa.Column("profile_created", sa.Boolean(), nullable=False),
        sa.Column("reset_password_token", sa.String(length=255), nullable=True),
        sa.Column("password_created", sa.Boolean(), nullable=False),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_address_id"],
            ["address.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["permanent_address_id"],
            ["address.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "attendance_leave_module",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("leave_type_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column(
            "start_half", sa.Enum("first_half", "second_half", name="half_day_enum"), nullable=False
        ),
        sa.Column("is_planned", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "cancelled", name="leave_status_enum"),
            nullable=False,
        ),
        sa.Column("total_days", sa.Integer(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "end_half", sa.Enum("first_half", "second_half", name="half_day_enum"), nullable=False
        ),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("documents", sa.Text(), nullable=True),
        sa.Column("notify_to_id", mysql.CHAR(length=36), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["leave_type_id"],
            ["organization_leaves_settings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["notify_to_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendance_leave_module_leave_type_id"),
        "attendance_leave_module",
        ["leave_type_id"],
        unique=False,
    )
    op.create_table(
        "client_inquires_data",
        sa.Column("form_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("form_name", sa.String(length=255), nullable=False),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("data", mysql.JSON(), nullable=True),
        sa.Column("client_inquire_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_inquire_id"], ["client_inquires.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config_model_department",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("department_name", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("default", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("config_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_module_id"], ["config_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config_model_designations",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("designations_name", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("default", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("config_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_module_id"], ["config_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config_model_project_status",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("status_name", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("default", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("status_color", sa.String(length=255), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("config_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_module_id"], ["config_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config_role_module",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("role_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=355), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("default", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("is_editable", sa.Boolean(), nullable=True),
        sa.Column("config_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_module_id"], ["config_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "family_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("father_name", sa.String(length=255), nullable=False),
        sa.Column("mother_name", sa.String(length=255), nullable=False),
        sa.Column("marital_status", mysql.CHAR(length=36), nullable=False),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inquiry_form_schema",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("form_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("form_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum("default", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("config_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("email_notification", sa.Boolean(), nullable=True),
        sa.Column("authorized_recipient_emails", sa.Text(), nullable=True),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_module_id"], ["config_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("form_id"),
        sa.UniqueConstraint("form_name"),
    )
    op.create_table(
        "leave_balance",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("leave_type_id", mysql.CHAR(length=36), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("available_leaves", sa.Integer(), nullable=False),
        sa.Column("last_refill_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["leave_type_id"], ["organization_leaves_settings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "organization_holidays",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("holiday_name", sa.String(length=255), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum("default", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("config_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_module_id"], ["config_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_updates",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("images", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("isCommentDisabled", sa.Boolean(), nullable=True),
        sa.Column("isLikeDisabled", sa.Boolean(), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("default", "system", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_updates_user_id"), "organization_updates", ["user_id"], unique=False
    )
    op.create_table(
        "personal_contact_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("personal_email", sa.String(length=255), nullable=False),
        sa.Column("mobile_number", sa.String(length=255), nullable=False),
        sa.Column("country_info", mysql.JSON(), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "personal_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("normalized_full_name", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("middle_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("profile_picture", sa.String(length=255), nullable=True),
        sa.Column("profile_picture_bg", sa.String(length=255), nullable=True),
        sa.Column("gender", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.DateTime(), nullable=True),
        sa.Column("blood_group", sa.String(length=255), nullable=False),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("ip_address", sa.String(length=255), nullable=True),
        sa.Column("browser", sa.String(length=255), nullable=True),
        sa.Column("browser_version", sa.String(length=255), nullable=True),
        sa.Column("os", sa.String(length=255), nullable=True),
        sa.Column("os_version", sa.String(length=255), nullable=True),
        sa.Column("device_type", sa.String(length=255), nullable=True),
        sa.Column("is_mobile", sa.Boolean(), nullable=True),
        sa.Column("is_tablet", sa.Boolean(), nullable=True),
        sa.Column("is_pc", sa.Boolean(), nullable=True),
        sa.Column("is_bot", sa.Boolean(), nullable=True),
        sa.Column("fingerprint", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "social_link",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("link", sa.String(length=255), nullable=True),
        sa.Column("target_blank", sa.Boolean(), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attendance_leave_notify",
        sa.Column("leave_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["leave_id"],
            ["attendance_leave_module.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("leave_id", "user_id"),
    )
    op.create_table(
        "children",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("child_name", sa.String(length=255), nullable=True),
        sa.Column("child_date_of_birth", sa.DateTime(), nullable=True),
        sa.Column("family_info_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_info_id"],
            ["family_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config_role_associated_permissions",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("module_label", sa.String(length=255), nullable=False),
        sa.Column("module_title", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("role_module_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("parent_module_id", mysql.CHAR(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_module_id"],
            ["config_role_associated_permissions.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_module_id"], ["config_role_module.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "emergency_contacts",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("emergency_contact_name", sa.String(length=255), nullable=False),
        sa.Column("emergency_contact_number", sa.String(length=255), nullable=False),
        sa.Column("emergency_contact_country_info", mysql.JSON(), nullable=True),
        sa.Column("contact_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["personal_contact_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "employee_info",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("status", sa.String(length=255), nullable=False),
        sa.Column("employee_type", sa.String(length=255), nullable=True),
        sa.Column("organization_name", sa.String(length=255), nullable=False),
        sa.Column("employee_code", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=255), nullable=False),
        sa.Column("designation", sa.String(length=255), nullable=False),
        sa.Column("joining_date", sa.DateTime(), nullable=True),
        sa.Column("employee_role_id", mysql.CHAR(length=36), nullable=True),
        sa.Column("employee_email", sa.String(length=255), nullable=False),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("reporting_to_id", mysql.CHAR(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_role_id"],
            ["config_role_module.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporting_to_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "feed_comments",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("is_replay", sa.Boolean(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("parent_id", mysql.CHAR(length=36), nullable=True),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("organization_update_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_update_id"], ["organization_updates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["feed_comments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feed_comments_organization_update_id"),
        "feed_comments",
        ["organization_update_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feed_comments_parent_id"), "feed_comments", ["parent_id"], unique=False
    )
    op.create_index(op.f("ix_feed_comments_user_id"), "feed_comments", ["user_id"], unique=False)
    op.create_table(
        "feed_likes",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("organization_update_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_update_id"], ["organization_updates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feed_likes_organization_update_id"),
        "feed_likes",
        ["organization_update_id"],
        unique=False,
    )
    op.create_index(op.f("ix_feed_likes_user_id"), "feed_likes", ["user_id"], unique=False)
    op.create_table(
        "inquiry_form_fields",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("field_name", sa.String(length=255), nullable=False),
        sa.Column("is_required_field", sa.Boolean(), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("default", "user_created", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("inquiry_form_schema_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["inquiry_form_schema_id"],
            ["inquiry_form_schema.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "permission_modules",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("is_allowed", sa.Boolean(), nullable=False),
        sa.Column("show_input", sa.Boolean(), nullable=False),
        sa.Column("associated_permissions_module_id", mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["associated_permissions_module_id"],
            ["config_role_associated_permissions.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permission_modules")
    op.drop_table("inquiry_form_fields")
    op.drop_index(op.f("ix_feed_likes_user_id"), table_name="feed_likes")
    op.drop_index(op.f("ix_feed_likes_organization_update_id"), table_name="feed_likes")
    op.drop_table("feed_likes")
    op.drop_index(op.f("ix_feed_comments_user_id"), table_name="feed_comments")
    op.drop_index(op.f("ix_feed_comments_parent_id"), table_name="feed_comments")
    op.drop_index(op.f("ix_feed_comments_organization_update_id"), table_name="feed_comments")
    op.drop_table("feed_comments")
    op.drop_table("employee_info")
    op.drop_table("emergency_contacts")
    op.drop_table("config_role_associated_permissions")
    op.drop_table("children")
    op.drop_table("attendance_leave_notify")
    op.drop_table("social_link")
    op.drop_table("session")
    op.drop_table("personal_info")
    op.drop_table("personal_contact_info")
    op.drop_index(op.f("ix_organization_updates_user_id"), table_name="organization_updates")
    op.drop_table("organization_updates")
    op.drop_table("organization_holidays")
    op.drop_table("leave_balance")
    op.drop_table("inquiry_form_schema")
    op.drop_table("family_info")
    op.drop_table("config_role_module")
    op.drop_table("config_model_project_status")
    op.drop_table("config_model_designations")
    op.drop_table("config_model_department")
    op.drop_table("client_inquires_data")
    op.drop_index(
        op.f("ix_attendance_leave_module_leave_type_id"), table_name="attendance_leave_module"
    )
    op.drop_table("attendance_leave_module")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("social_media_posts")
    op.drop_table("social_media_accounts")
    op.drop_table("organization_updates_admin")
    op.drop_table("organization_settings")
    op.drop_index(
        op.f("ix_organization_leaves_settings_organization_id"),
        table_name="organization_leaves_settings",
    )
    op.drop_table("organization_leaves_settings")
    op.drop_table("organization_general_info")
    op.drop_table("organization_contact_info")
    op.drop_table("organization_address")
    op.drop_table("organization_about_info")
    op.drop_table("orbit_admin_session")
    op.drop_table("maintenance_logs")
    op.drop_table("config_module")
    op.drop_table("client_inquires")
    op.drop_table("organization")
    op.drop_table("orbit_admin")
    op.drop_table("maintenance_mode")
    op.drop_table("address")
    # ### end Alembic commands ###
