"""automated-migration

Revision ID: 97a91aed9215
Revises: 6cd057e0c562
Create Date: 2025-12-05 21:54:34.400729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a91aed9215'
down_revision: Union[str, None] = '6cd057e0c562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_location_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'user_location_info')
    # ### end Alembic commands ###
