"""automated-migration

Revision ID: 9a4f6206abb8
Revises: a52d486acb19
Create Date: 2026-03-01 14:45:45.941263

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a4f6206abb8"
down_revision: Union[str, None] = "a52d486acb19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
ALTER TABLE attendance_leave_module
MODIFY COLUMN status ENUM('pending','approved','cancelled','rejected')
NOT NULL DEFAULT 'pending'
"""
    )


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
