"""automated-migration

Revision ID: a211d69e594e
Revises: 2accbfadd751
Create Date: 2025-08-17 18:13:56.471743

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a211d69e594e"
down_revision: Union[str, None] = "2accbfadd751"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("social_media_posts", sa.Column("caption", sa.Text(), nullable=False))
    op.add_column("social_media_posts", sa.Column("media_urls", sa.Text(), nullable=True))
    op.add_column(
        "social_media_posts",
        sa.Column("type", sa.Enum("default", "scheduled", name="post_type_enum"), nullable=False),
    )
    op.add_column(
        "social_media_posts",
        sa.Column(
            "status",
            sa.Enum("queued", "scheduled", "posted", name="post_status_enum"),
            nullable=False,
        ),
    )
    op.add_column("social_media_posts", sa.Column("scheduled_on", sa.DateTime(), nullable=True))
    op.add_column("social_media_posts", sa.Column("post_id", sa.String(length=255), nullable=True))
    op.add_column("social_media_posts", sa.Column("posted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "social_media_posts", sa.Column("organization_id", mysql.CHAR(length=36), nullable=False)
    )
    op.add_column("social_media_posts", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.drop_constraint("social_media_posts_ibfk_1", "social_media_posts", type_="foreignkey")
    op.create_foreign_key(
        None,
        "social_media_posts",
        "organization",
        ["organization_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("social_media_posts", "media_url")
    op.drop_column("social_media_posts", "account_id")
    op.drop_column("social_media_posts", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("social_media_posts", sa.Column("content", mysql.TEXT(), nullable=False))
    op.add_column(
        "social_media_posts", sa.Column("account_id", mysql.CHAR(length=36), nullable=False)
    )
    op.add_column(
        "social_media_posts", sa.Column("media_url", mysql.VARCHAR(length=255), nullable=True)
    )
    op.drop_constraint(None, "social_media_posts", type_="foreignkey")
    op.create_foreign_key(
        "social_media_posts_ibfk_1",
        "social_media_posts",
        "social_media_accounts",
        ["account_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("social_media_posts", "updated_at")
    op.drop_column("social_media_posts", "organization_id")
    op.drop_column("social_media_posts", "posted_at")
    op.drop_column("social_media_posts", "post_id")
    op.drop_column("social_media_posts", "scheduled_on")
    op.drop_column("social_media_posts", "status")
    op.drop_column("social_media_posts", "type")
    op.drop_column("social_media_posts", "media_urls")
    op.drop_column("social_media_posts", "caption")
    # ### end Alembic commands ###
