"""automated-migration

Revision ID: a303347c6f6d
Revises: b6af7663b167
Create Date: 2025-07-17 17:01:33.549286

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a303347c6f6d"
down_revision: Union[str, None] = "b6af7663b167"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orbit_admin_session", sa.Column("admin_id", mysql.CHAR(length=36), nullable=False)
    )
    op.drop_constraint("orbit_admin_session_ibfk_1", "orbit_admin_session", type_="foreignkey")
    op.create_foreign_key(
        None,
        "orbit_admin_session",
        "orbit_admin",
        ["admin_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("orbit_admin_session", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orbit_admin_session", sa.Column("user_id", mysql.CHAR(length=36), nullable=False)
    )
    op.drop_constraint(None, "orbit_admin_session", type_="foreignkey")
    op.create_foreign_key(
        "orbit_admin_session_ibfk_1",
        "orbit_admin_session",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("orbit_admin_session", "admin_id")
    # ### end Alembic commands ###
