"""automated-migration

Revision ID: a66acba7ab4e
Revises: 2b619fcc6f97
Create Date: 2026-06-12 14:43:08.306948

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a66acba7ab4e"
down_revision: Union[str, None] = "2b619fcc6f97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inquiry_form_schema", sa.Column("turnstile_widget_name", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inquiry_form_schema", "turnstile_widget_name")
    # ### end Alembic commands ###
