"""automated-migration

Revision ID: ac443f6019b1
Revises: 74e816fc888a
Create Date: 2026-06-13 15:36:48.986773

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ac443f6019b1"
down_revision: Union[str, None] = "74e816fc888a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inquiry_form_schema",
        sa.Column(
            "turnstile_verification_status",
            sa.Enum("pending_verification", "verified", name="turnstile_verification_status_enum"),
            nullable=False,
        ),
    )
    op.drop_column("inquiry_form_schema", "turnstile_setup_mode")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inquiry_form_schema", sa.Column("turnstile_setup_mode", mysql.ENUM("automated", "manual"), nullable=False)
    )
    op.drop_column("inquiry_form_schema", "turnstile_verification_status")
    # ### end Alembic commands ###
