"""automated-migration

Revision ID: b6af7663b167
Revises: cf9f6ae8867b
Create Date: 2025-07-17 16:48:34.053057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6af7663b167'
down_revision: Union[str, None] = 'cf9f6ae8867b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orbit_admin', 'admin_signature')
    op.drop_column('orbit_admin', 'reset_token')
    op.add_column('orbit_admin_session', sa.Column('admin_signature', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orbit_admin_session', 'admin_signature')
    op.add_column('orbit_admin', sa.Column('reset_token', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orbit_admin', sa.Column('admin_signature', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
