"""automated-migration

Revision ID: b9e455ca4c15
Revises: 924dad1ad813
Create Date: 2025-09-20 15:38:29.970918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b9e455ca4c15'
down_revision: Union[str, None] = '924dad1ad813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_inquires_data', 'authorized_recipient_emails')
    op.drop_column('client_inquires_data', 'email_notification')
    op.add_column('inquiry_form_schema', sa.Column('email_notification', sa.Boolean(), nullable=True))
    op.add_column('inquiry_form_schema', sa.Column('authorized_recipient_emails', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inquiry_form_schema', 'authorized_recipient_emails')
    op.drop_column('inquiry_form_schema', 'email_notification')
    op.add_column('client_inquires_data', sa.Column('email_notification', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('client_inquires_data', sa.Column('authorized_recipient_emails', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
