"""automated-migration

Revision ID: cd2d8ab98dd6
Revises: 0ae3977fcd3e
Create Date: 2025-11-05 15:43:37.583603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2d8ab98dd6'
down_revision: Union[str, None] = '0ae3977fcd3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config_role_module', sa.Column('is_editable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config_role_module', 'is_editable')
    # ### end Alembic commands ###
