"""automated-migration

Revision ID: eeb7a4a4986e
Revises: 265bd56cbd42
Create Date: 2025-08-12 03:29:46.649304

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "eeb7a4a4986e"
down_revision: Union[str, None] = "265bd56cbd42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feed_comments", sa.Column("is_replay", sa.Boolean(), nullable=False))
    op.add_column("feed_comments", sa.Column("comment", sa.Text(), nullable=True))
    op.add_column("feed_comments", sa.Column("user_id", mysql.CHAR(length=36), nullable=False))
    op.add_column(
        "feed_comments", sa.Column("organization_update_id", mysql.CHAR(length=36), nullable=False)
    )
    op.drop_index("ix_feed_comments_id", table_name="feed_comments")
    op.create_index(
        op.f("ix_feed_comments_organization_update_id"),
        "feed_comments",
        ["organization_update_id"],
        unique=False,
    )
    op.create_index(op.f("ix_feed_comments_user_id"), "feed_comments", ["user_id"], unique=False)
    op.create_foreign_key(
        None,
        "feed_comments",
        "organization_updates",
        ["organization_update_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(None, "feed_comments", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "feed_comments", type_="foreignkey")
    op.drop_constraint(None, "feed_comments", type_="foreignkey")
    op.drop_index(op.f("ix_feed_comments_user_id"), table_name="feed_comments")
    op.drop_index(op.f("ix_feed_comments_organization_update_id"), table_name="feed_comments")
    op.create_index("ix_feed_comments_id", "feed_comments", ["id"], unique=False)
    op.drop_column("feed_comments", "organization_update_id")
    op.drop_column("feed_comments", "user_id")
    op.drop_column("feed_comments", "comment")
    op.drop_column("feed_comments", "is_replay")
    # ### end Alembic commands ###
