"""automated-migration

Revision ID: f215e79e6af6
Revises: 75cb63854ed5
Create Date: 2025-11-10 17:21:57.819729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f215e79e6af6'
down_revision: Union[str, None] = '75cb63854ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_balance', sa.Column('leave_type_id', mysql.CHAR(length=36), nullable=True))
    op.add_column('leave_balance', sa.Column('user_id', mysql.CHAR(length=36), nullable=False))
    op.add_column('leave_balance', sa.Column('available_leaves', sa.Integer(), nullable=False))
    op.add_column('leave_balance', sa.Column('last_refill_date', sa.Date(), nullable=True))
    op.add_column('leave_balance', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('leave_balance', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'leave_balance', ['user_id'])
    op.create_foreign_key(None, 'leave_balance', 'organization_leaves_settings', ['leave_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'leave_balance', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leave_balance', type_='foreignkey')
    op.drop_constraint(None, 'leave_balance', type_='foreignkey')
    op.drop_constraint(None, 'leave_balance', type_='unique')
    op.drop_column('leave_balance', 'updated_at')
    op.drop_column('leave_balance', 'created_at')
    op.drop_column('leave_balance', 'last_refill_date')
    op.drop_column('leave_balance', 'available_leaves')
    op.drop_column('leave_balance', 'user_id')
    op.drop_column('leave_balance', 'leave_type_id')
    # ### end Alembic commands ###
