"""automated-migration

Revision ID: 3802af87506e
Revises: 869435761a6d
Create Date: 2025-12-05 15:59:36.291335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3802af87506e'
down_revision: Union[str, None] = '869435761a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_general_info', sa.Column('indexed_email_domain', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_organization_general_info_indexed_email_domain'), 'organization_general_info', ['indexed_email_domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_general_info_indexed_email_domain'), table_name='organization_general_info')
    op.drop_column('organization_general_info', 'indexed_email_domain')
    # ### end Alembic commands ###
