"""automated-migration

Revision ID: 80d326ed7596
Revises: b659f648fca3
Create Date: 2026-07-04 17:02:21.218621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "80d326ed7596"
down_revision: Union[str, None] = "b659f648fca3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "organization_about_info",
        "about",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization_about_info",
        "about",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )

    # ### end Alembic commands ###
