"""automated-migration

Revision ID: b659f648fca3
Revises: d4dd86380bdd
Create Date: 2026-06-08 16:48:19.197306

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b659f648fca3"
down_revision: Union[str, None] = "d4dd86380bdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_locations_config",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("location_name", sa.String(length=255), nullable=False),
        sa.Column("location_coordinates", sa.Text(), nullable=False),
        sa.Column("allowed_radius_meters", sa.Integer(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("organization_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_by", mysql.JSON(), nullable=True),
        sa.Column("updated_by", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_locations_config_organization_id"),
        "organization_locations_config",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "attendance_punch_in_out_module",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("punch_in_time", sa.DateTime(), nullable=False),
        sa.Column("punch_out_time", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "completed", "system_ended", name="attendance_punch_in_out_module_status_enum"),
            nullable=True,
        ),
        sa.Column("punch_in_coordinates", sa.Text(), nullable=False),
        sa.Column("punch_out_coordinates", sa.Text(), nullable=True),
        sa.Column("is_mislinious", sa.Boolean(), nullable=False),
        sa.Column("total_effective_minutes", sa.Integer(), nullable=True),
        sa.Column("total_break_minutes", sa.Integer(), nullable=True),
        sa.Column("total_gross_minutes", sa.Integer(), nullable=True),
        sa.Column("is_work_from_home", sa.Boolean(), nullable=False),
        sa.Column("is_regularize_required", sa.Boolean(), nullable=False),
        sa.Column("session_completed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attendance_break_model",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("session_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("break_start_time", sa.DateTime(), nullable=False),
        sa.Column("break_end_time", sa.DateTime(), nullable=True),
        sa.Column("total_break_minutes", sa.Float(), nullable=True),
        sa.Column("punch_in_coordinates", sa.Text(), nullable=True),
        sa.Column("punch_out_coordinates", sa.Text(), nullable=True),
        sa.Column("is_mislinious", sa.Boolean(), nullable=False),
        sa.Column("status", sa.Enum("active", "completed", "system_ended", name="break_status_enum"), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["attendance_punch_in_out_module.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Add as nullable first because table already has existing rows
    op.add_column(
        "client_inquires_data",
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )

    op.add_column(
        "client_inquires_data",
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    # Fill old rows with valid datetime
    op.execute("""
    UPDATE client_inquires_data
    SET 
        created_at = NOW(),
        updated_at = NOW()
    WHERE created_at IS NULL OR updated_at IS NULL
""")

    # Now make created_at NOT NULL
    op.alter_column(
        "client_inquires_data",
        "created_at",
        existing_type=sa.DateTime(),
        nullable=False,
    )
    # op.drop_index("user_id", table_name="leave_balance")
    op.add_column("organization_settings", sa.Column("total_gross_hours", sa.Integer(), nullable=True))
    op.add_column("organization_settings", sa.Column("total_effective_hours", sa.Integer(), nullable=True))
    op.add_column("organization_settings", sa.Column("half_day_gross_hours", sa.Integer(), nullable=True))
    op.add_column("organization_settings", sa.Column("half_day_effective_hours", sa.Integer(), nullable=True))
    op.add_column("organization_settings", sa.Column("error_corratin_metting", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_settings", "error_corratin_metting")
    op.drop_column("organization_settings", "half_day_effective_hours")
    op.drop_column("organization_settings", "half_day_gross_hours")
    op.drop_column("organization_settings", "total_effective_hours")
    op.drop_column("organization_settings", "total_gross_hours")
    # op.create_index("user_id", "leave_balance", ["user_id"], unique=True)
    op.drop_column("client_inquires_data", "updated_at")
    op.drop_column("client_inquires_data", "created_at")
    op.drop_table("attendance_break_model")
    op.drop_table("attendance_punch_in_out_module")
    op.drop_index(op.f("ix_organization_locations_config_organization_id"), table_name="organization_locations_config")
    op.drop_table("organization_locations_config")
    # ### end Alembic commands ###
