"""automated-migration

Revision ID: d4dd86380bdd
Revises: 8a13d2597080
Create Date: 2026-01-20 21:27:57.327922

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d4dd86380bdd"
down_revision: Union[str, None] = "8a13d2597080"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attendance_leave_module",
        "start_date",
        existing_type=sa.DATE(),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "attendance_leave_module",
        "total_days",
        existing_type=mysql.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "attendance_leave_module",
        "end_date",
        existing_type=sa.DATE(),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("user_id", "leave_balance", ["user_id"], unique=True)
    op.alter_column(
        "attendance_leave_module",
        "end_date",
        existing_type=sa.String(length=255),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "attendance_leave_module",
        "total_days",
        existing_type=sa.Float(),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "attendance_leave_module",
        "start_date",
        existing_type=sa.String(length=255),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
