name: CI/CD Pipeline

on:
  push:
    branches:
      - production # or development branch

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: varun
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /home/varun/OrbitRMS-Backend
            git fetch origin
            git reset --hard origin/main
            source venv/bin/activate
            pip install -r requirements.txt
            # Optionally run migration or build scripts here
            sudo systemctl restart orbitrms
